//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEAS
    {
        public int NumFact { get; set; }
        public int CodArt { get; set; }
        public int Cant { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
