//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio
{
    public partial class ABMUsuarios
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.Button btnCrear;
        protected global::System.Web.UI.WebControls.Button btnModificar;
        protected global::System.Web.UI.WebControls.Button btnPassword;
        protected global::System.Web.UI.WebControls.Button btnEliminar;
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
    }
}
