//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio
{
    public partial class AltaMensaje
    {
        protected global::System.Web.UI.WebControls.Label lblResultado;
        protected global::System.Web.UI.WebControls.TextBox txtRemitente;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategorias;
        protected global::System.Web.UI.WebControls.TextBox txtAsunto;
        protected global::System.Web.UI.WebControls.TextBox txtTexto;
        protected global::System.Web.UI.WebControls.TextBox txtCaducidad;
        protected global::System.Web.UI.WebControls.TextBox txtDestinatarios;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
    }
}
