//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio
{
    public partial class Bandeja
    {
        protected global::System.Web.UI.WebControls.Label lblInfo;
        protected global::System.Web.UI.WebControls.TextBox txtUsuario;
        protected global::System.Web.UI.WebControls.Button btnBandeja;
        protected global::System.Web.UI.WebControls.Button btnEnviados;
        protected global::System.Web.UI.WebControls.GridView gvMensajes;
    }
}
