//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblTotalUsuarios;
        protected global::System.Web.UI.WebControls.Label lblMensajesActivos;
        protected global::System.Web.UI.WebControls.Label lblMensajesVencidos;
        protected global::System.Web.UI.WebControls.Label lblMensajesMasCinco;
    }
}
